name: dm2_adna
channels:
  - conda-forge
  - bioconda
dependencies:
  - numpy
  - pysam
  - python>=3.8
  - pytorch
  - h5py
  - tqdm
  - numba
  - ont-fast5-api
  - samtools
  - matplotlib
  - pandas
  - scipy
  - pip
  - scikit-learn
  - pip:
    - pod5

